name: Build doc and release

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build_pdf:
    runs-on: ubuntu-latest
    name: Build PDF
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Requirements
      run: |
        sudo apt install fonts-roboto
        sudo fc-cache -f -v
        sudo apt-get install texlive-xetex
        sudo apt-get install pandoc
    - name: Build
      run: |
        ./.github/workflows/build_document.sh
        ls -la .
    - name: Archive artifacts
      uses: actions/upload-artifact@v2
      with:
        name: pdf_document
        path: my_built_document_*.pdf

#################################################################################
# A number of variables must be set for the jobs to work. 
#
#   - ZENODO_URL:                    - Zenodo URL to deposit release file to.
#
#   - ZENODO_TOKEN:                  - Zenodo access token.
#
#   - ZENODO_DEPOSIT_ID:             - Deposit ID of previous Zenodo deposit.
###############################################################################

  upload_zenodo:
    runs-on: ubuntu-latest
    needs: build_pdf
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Download result for build_pdf
        uses: actions/download-artifact@v2
        with:
          name: pdf_document
      - name: Deposit
        env: # Or as an environment variable
          ZENODO_URL: ${{ secrets.ZENODO_URL }}
          ZENODO_TOKEN: ${{ secrets.ZENODO_TOKEN }}
          ZENODO_DEPOSIT_ID: ${{ secrets.ZENODO_DEPOSIT_ID }}
        run: ./.github/workflows/zenodo_deposit.sh "$ZENODO_URL" "$ZENODO_TOKEN" "$ZENODO_DEPOSIT_ID"
