name: Build doc and release

on:
  release:
  workflow_dispatch:

jobs:
  build_pdf:
    runs-on: ubuntu-latest
    name: Build PDF
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Requirements
      run: |
        sudo apt install fonts-roboto
        sudo fc-cache -f -v
        sudo fc-list
        sudo apt-get install texlive-xetex
        sudo apt-get install pandoc
    - name: Build
      run: |
        ./.github/workflows/build_document.sh
        ls -la . 
  # upload_zenodo:
  #   runs-on: ubuntu-latest
  #   needs: build_pdf
